#!/bin/sh

### 'ls' aliases ###
alias ll='la -alF'
alias la='ls -A'
alias lla='ls -lAh'
alias llA='ls -lah'
alias l='ls -F1'

# alias 'sudo ll'='sudo ls -lh'
# alias 'sudo la'='sudo ls -A'
# alias 'sudo lla'='sudo ls -lAh'
# alias 'sudo llA'='sudo ls -lah'
# alias 'sudo l'='sudo ls -CF1'

# alias -g rm='rm -Iv'
# alias -g cp='cp -iv --reflink=auto'
# alias -g mv='mv -iv'
# alias -g ln='ln -iv'

### Text editor ###
alias v="$EDITOR"
alias vi="$EDITOR"
alias vim="$EDITOR"
alias nv='v'

### Navigation upstream ###
alias ..='cd ..'
alias ...='cd ../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

### Make tmux assume 256-color support ###
alias tmux='tmux -2'

### Default to Python 3 ###
alias python=python3

### Refresh Bash ###
alias refresh='source ~/.bash_profile'

### Stupid Things ###
alias walker=neofetch

### UBUNTU ALERT ALIAS
# Sends a desktop notification when a long-running command completes
# Sample usage : sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
